## ´İ’è #############################################################
chara_folder	l_shizuku,"chara"
chara_name	l_shizuku,"´"
@shizuku_small
@shizuku_shifuku

## Á‚· #######################################################################
macro	shizuku_
	chara_off	l_shizuku
endmacro

## ‹——£ #######################################################################
# ‰“‚¢
macro	shizuku_small
	chara_size	l_shizuku,"¬",0,11
endm

# ‰“‚¢
macro	shizuku_small_left
	chara_size	l_shizuku,"¬",-200,11
endm



# ’†ŠÔ
macro	shizuku_middle
	chara_size	l_shizuku,"’†",0,-104
endm

# ‹ß‚¢
macro	shizuku_large
	chara_size	l_shizuku,"‘å",0,-74
endm

## •‘• ######################################################################
macro	shizuku_shifuku
	chara_clothes	l_shizuku,"„•"
endm
macro	shizuku_mizugi
	chara_clothes	l_shizuku,"…’…"
endm
macro	shizuku_hadaka
	chara_clothes	l_shizuku,"—‡"
endm

## •\î ######################################################################

#- •’Ê ----------------------------------------------------------------------
macro	shizuku
	chara_auto	l_shizuku,"•’Ê.png"
endm
#- •ğ ------------------------------------------------------------------------
macro	shizuku_akire
	chara_auto	l_shizuku,"•ğ.png"
endm
#- “{Î‚¢ --------------------------------------------------------------------
macro	shizuku_ikariwarai
	chara_auto	l_shizuku,"“{Î.png"
endm
#- “{Î‚¢ --------------------------------------------------------------------
macro	shizuku_chousyou
	chara_auto	l_shizuku,"“{Î.png"
endm
#- “{‚è ----------------------------------------------------------------------
macro	shizuku_ikari
	chara_auto	l_shizuku,"“{.png"
endm
#- Î‚¢ ----------------------------------------------------------------------
macro	shizuku_warai
#	chara_auto	l_shizuku,"Î.png"
	chara_auto	l_shizuku,"“{Î.png"
endm
macro	shizuku_warai2
	chara_auto	l_shizuku,"Î.png"
endm
#- Æ‚ê“{‚è ------------------------------------------------------------------
macro	shizuku_tereikari
	chara_auto	l_shizuku,"Æ“{.png"
endm
#- Æ‚ê‚·‚Ë ------------------------------------------------------------------
macro	shizuku_teresune
	chara_auto	l_shizuku,"Æ‚·‚Ë.png"
endm
#- Æ‚ê‚·‚Ë ------------------------------------------------------------------
macro	shizuku_tere
	chara_auto	l_shizuku,"Æ.png"
endm
#- ‹ƒ‚« ----------------------------------------------------------------------
macro	shizuku_naki
	chara_auto	l_shizuku,"‹ƒ.png"
endm
#- Šì‚Ñ ----------------------------------------------------------------------
macro	shizuku_yorokobi
	chara_auto	l_shizuku,"Šì.png"
endm
#- ˆ£ ----------------------------------------------------------------------
macro	shizuku_kanashimi
	chara_auto	l_shizuku,"•ğ.png"
endm

