## ‚´‚­‚ëİ’è #############################################################
chara_folder	l_zakuro,"chara"
chara_name	l_zakuro,"‚´‚­‚ë"
@zakuro_small
@zakuro_shifuku

## Á‚· #######################################################################
macro	zakuro_
	chara_off	l_zakuro
endmacro

## ‹——£ #######################################################################
# ‰“‚¢
macro	zakuro_small
	chara_size	l_zakuro,"¬",0,80
endm

# ’†ŠÔ
macro	zakuro_middle
	chara_size	l_zakuro,"’†",0,-35
endm

# ‹ß‚¢
macro	zakuro_large
	chara_size	l_zakuro,"‘å",64,0
endm

## •‘• ######################################################################
macro	zakuro_shifuku
	chara_clothes	l_zakuro,"„•"
endm
macro	zakuro_mizugi
	chara_clothes	l_zakuro,"…’…"
endm
macro	zakuro_pajama
	chara_clothes	l_zakuro,"•”‰®’…"
endm
macro	zakuro_shitagi
	chara_clothes	l_zakuro,"‰º’…"
endm
macro	zakuro_hadaka
	chara_clothes	l_zakuro,"—‡"
endm

## •\î ######################################################################

#- •’Ê ----------------------------------------------------------------------
macro	zakuro
	chara_auto	l_zakuro,"•.png"
endm
#- •ğ ------------------------------------------------------------------------
macro	zakuro_akire
	chara_auto	l_zakuro,"•ğ.png"
endm
#- –Ú•Â‚¶ --------------------------------------------------------------------
macro	zakuro_metoji
	chara_auto	l_zakuro,"•Â.png"
endm
#- “{‚è ----------------------------------------------------------------------
macro	zakuro_ikari
	chara_auto	l_zakuro,"“{.png"
endm
#- Î‚¢ ----------------------------------------------------------------------
macro	zakuro_warai
	chara_auto	l_zakuro,"‚É‚±.png"
endm
#- Î‚¢2 ----------------------------------------------------------------------
macro	zakuro_warai2
	chara_auto	l_zakuro,"Î.png"
endm
#- Œ™ ------------------------------------------------------------------------
macro	zakuro_iya
	chara_auto	l_zakuro,"Œ™.png"
endm
#- ‚É‚± ----------------------------------------------------------------------
macro	zakuro_niko
	chara_auto	l_zakuro,"‚É‚±.png"
endm
#- ˆ£‚µ‚İ ----------------------------------------------------------------------
macro	zakuro_kanashimi
	chara_auto	l_zakuro,"ˆ£.png"
endm
#- Æ‚ê ----------------------------------------------------------------------
macro	zakuro_tere
	chara_auto	l_zakuro,"Æ.png"
endm
