#BGM 定義
#BGM 01 : 雨のテーマ
macro	bgm01
	bgm_loopin	"sound\bgm\m01.ogg",249776
endm

#BGM 02 : 朝のテーマ
macro	bgm02
	bgm_loopin	"sound\bgm\m02.ogg",2118684
endm

#BGM 03 : いちごのテーマ
macro	bgm03
	bgm_loopin	"sound\bgm\m03.ogg",546340
endm

#BGM 04 : スケジュール実行中のテーマ
macro	bgm04
	bgm		"sound\bgm\m04.ogg",play_loop
endm

#BGM 05 : 悲しいシーンの曲
macro	bgm05
	bgm_loopin	"sound\bgm\m05.ogg",193072
endm

#BGM 06 : 不安のテーマ
macro	bgm06
	bgm		"sound\bgm\m06.ogg",play_loop
endm

#BGM 07 : 戦闘のテーマ
macro	bgm07
	bgm_loopin	"sound\bgm\m07.ogg",170944
endm

#BGM 08 : 美雨のテーマ
macro	bgm08
	bgm		"sound\bgm\m08.ogg",play_loop
endm

#BGM 09 : 緊迫したシーンの曲
macro	bgm09
	bgm_loopin	"sound\bgm\m09.ogg",318520
endm

#BGM 10 : エッチシーンのテーマ
macro	bgm10
	bgm		"sound\bgm\m10.ogg",play_loop
endm

#BGM 11 : 暗いエッチのテーマ
macro	bgm11
	bgm		"sound\bgm\m11.ogg",play_loop
endm

#BGM 12 : メインテーマ
macro	bgm12
	bgm_loopin	"sound\bgm\m12.ogg",282436
endm

#BGM 13 : エンディング/スタッフロール
macro	bgm13
	bgm_loopin	"sound\bgm\m13.ogg",2150668
endm

#BGM 14 : ショップ
macro	bgm14
	bgm		"sound\bgm\m14.ogg",play_loop
endm

#BGM 15 : スケジュール?
macro	bgm15
	bgm		"sound\bgm\m15.ogg",play_loop
endm

#BGM 16 : ミステリアス
macro	bgm16
	bgm_loopin	"sound\bgm\m16.ogg",4101296
endm

#BGM 17 : のんびりのテーマ
macro	bgm17
	bgm		"sound\bgm\m17.ogg",play_loop
endm

#BGM K01 : 夢のテーマ
macro	bgmk01
	bgm		"sound\bgm\mk01.ogg",play_loop
endm

#BGM K02 : しんみりのテーマ
macro	bgmk02
	bgm		"sound\bgm\mk02.ogg",play_loop
endm

#BGM K03 : 静かの時のテーマ
macro	bgmk03
	bgm		"sound\bgm\mk03.ogg",play_loop
endm

#BGM K04 : 寝る前のテーマ
macro	bgmk04
	bgm		"sound\bgm\mk04.ogg",play_loop
endm

#BGM K05 : 選択時のテーマ? テクノ風
macro	bgmk05
	bgm		"sound\bgm\mk05.ogg",play_loop
endm

#BGM K06 : 哀しいな時のテーマ
macro	bgmk06
	bgm		"sound\bgm\mk06.ogg",play_loop
endm

#BGM K07 : 深刻なテーマ
macro	bgmk07
	bgm		"sound\bgm\mk07.ogg",play_loop
endm

#BGM K08 : 不気味なテーマ
macro	bgmk08
	bgm		"sound\bgm\mk08.ogg",play_loop
endm

#BGM K09 : ラスト手前っぽいテーマ
macro	bgmk09
	bgm		"sound\bgm\mk09.ogg",play_loop
endm

#BGM K10 : 重い雰囲気テーマ
macro	bgmk10
	bgm		"sound\bgm\mk10.ogg",play_loop
endm

#BGM K11 : 夢のテーマ、その2
macro	bgmk11
	bgm		"sound\bgm\mk11.ogg",play_loop
endm

#BGM K12 : 興味津々のテーマ
macro	bgmk12
	bgm		"sound\bgm\mk12.ogg",play_loop
endm


#BGM K12 : 婚礼の合唱
macro	bgmkekkon
	bgm		"sound\bgm\婚礼の合唱.ogg",play_loop
endm
