## ”ü‰J—§‚¿İ’è #############################################################
chara_folder	l_suika,"chara"
chara_name	l_suika,"‚·‚¢‚©"
@suika_small
@suika_shifuku

## Á‚· #######################################################################
macro	suika_
	chara_off	l_suika
endmacro

## ‹——£ #######################################################################
# ‰“‚¢
macro	suika_small
	chara_size	l_suika,"¬",0,127
endm

# ’†ŠÔ
macro	suika_middle
	chara_size	l_suika,"’†",0,28
endm

# ‹ß‚¢
macro	suika_large
	chara_size	l_suika,"‘å",0,0
endm

## •‘• ######################################################################
macro	suika_shifuku
	chara_clothes	l_suika,"„•"
endm
macro	suika_mizugi
	chara_clothes	l_suika,"…’…"
endm
macro	suika_shitagi
	chara_clothes	l_suika,"‰º’…"
endm
macro	suika_seifuku
	chara_clothes	l_suika,"§•"
endm
macro	suika_heyagi
	chara_clothes	l_suika,"•”‰®’…"
endm
macro	suika_hadaka
	chara_clothes	l_suika,"—‡"
endm

## •\î ######################################################################

#- •’Ê ----------------------------------------------------------------------
macro	suika
	chara_auto	l_suika,"•.png"
endm
#- Î‚¢ ----------------------------------------------------------------------
macro	suika_warai
	chara_auto	l_suika,"Î.png"
endm
#- ˆ£ ------------------------------------------------------------------------
macro	suika_kanashimi
	chara_auto	l_suika,"ˆ£.png"
endm
#- Šì ------------------------------------------------------------------------
macro	suika_yorokobi
	chara_auto	l_suika,"Šì.png"
endm
#- ‹ƒ ------------------------------------------------------------------------
macro	suika_naki
	chara_auto	l_suika,"‹ƒ.png"
endm
#- ‹‘â ----------------------------------------------------------------------
macro	suika_kyozetsu
	chara_auto	l_suika,"‹‘â.png"
endm
#- ‹Á ------------------------------------------------------------------------
macro	suika_odoroki
	chara_auto	l_suika,"‹Á.png"
endm
#- ¢Î ----------------------------------------------------------------------
macro	suika_komariwarai
	chara_auto	l_suika,"¢Î.png"
endm
#- Æ ------------------------------------------------------------------------
macro	suika_tere
	chara_auto	l_suika,"Æ.png"
endm
#- ^Œ•“{‚è ------------------------------------------------------------------
macro	suika_shinkenikari
	chara_auto	l_suika,"^Œ•“{‚è.png"
endm
#- “{‚è ----------------------------------------------------------------------
macro	suika_ikari
	chara_auto	l_suika,"“{.png"
endm
#- ”­î_Šì -------------------------------------------------------------------
macro	suika_hatsujyou_yorokobi
	chara_auto	l_suika,"”­î_Šì.png"
endm
