## ˜@—§‚¿İ’è #############################################################
chara_folder	l_ren,"chara"
chara_name	l_ren,"˜@"
@ren_small
@ren_shifuku

## Á‚· #######################################################################
macro	ren_
	chara_off	l_ren
endmacro

## ‹——£ #######################################################################
# ‰“‚¢
macro	ren_small
	chara_size	l_ren,"¬",0,0
endm

# ’†ŠÔ
macro	ren_middle
	chara_size	l_ren,"’†",-64,-40
endm

# ‹ß‚¢
macro	ren_large
	chara_size	l_ren,"‘å",0,-78
endm

## •‘• ######################################################################
macro	ren_shifuku
	chara_clothes	l_ren,"„•"
endm
macro	ren_hadaka
	chara_clothes	l_ren,"—‡"
endm

## •\î ######################################################################

#- •’Ê ----------------------------------------------------------------------
macro	ren
	chara_auto	l_ren,"•.png"
endm
#- Î‚¢ ----------------------------------------------------------------------
macro	ren_warai
	chara_auto	l_ren,"Î.png"
endm
#- Æ‚ê ----------------------------------------------------------------------
macro	ren_tere
	chara_auto	l_ren,"Šì.png"
endm
#- “{‚è ----------------------------------------------------------------------
macro	ren_ikari
	chara_auto	l_ren,"“{.png"
endm
#- ‹Á‚« ----------------------------------------------------------------------
macro	ren_odoroki
	chara_auto	l_ren,"‹Á.png"
endm
#- ˆ£‚µ‚İ --------------------------------------------------------------------
macro	ren_kanashimi
	chara_auto	l_ren,"ˆ£.png"
endm
#- ‹ƒ‚« --------------------------------------------------------------------
macro	ren_naki
	chara_auto	l_ren,"‹ƒ.png"
endm
#- ‹ƒ‚«2 --------------------------------------------------------------------
macro	ren_naki2
	chara_auto	l_ren,"‹ƒ2.png"
endm
#- Šì‚Ñ --------------------------------------------------------------------
macro	ren_yorokobi
	chara_auto	l_ren,"Šì.png"
endm
