## ‘ƒŠWİ’è ##################################################################
chara_folder	l_subuta,"chara"
chara_name	l_subuta,"‘ƒŠW‚³‚ñ"
@subuta_small
@subuta_apron

## Á‚· #######################################################################
macro	subuta_
	chara_off	l_subuta
endmacro

## ‹——£ #######################################################################
# ‰“‚¢
macro	subuta_small
	chara_size	l_subuta,"¬",120,89
endm

# ‰“‚¢
macro	subuta_right
	chara_size	l_subuta,"¬",240,0
endm

# ’†ŠÔ
macro	subuta_middle
	chara_size	l_subuta,"’†",0,0
endm

# ‹ß‚¢
macro	subuta_large
	chara_size	l_subuta,"‘å",0,0
endm

## •‘• ######################################################################
macro	subuta_apron
	chara_clothes	l_subuta,"ƒGƒvƒƒ“"
endm
macro	subuta_counter
	chara_clothes	l_subuta,"ƒJƒEƒ“ƒ^["
endm

## •\î ######################################################################

#- •’Ê ----------------------------------------------------------------------
macro	subuta
	chara_auto	l_subuta,"•.png"
endm
#- “{‚è ----------------------------------------------------------------------
macro	subuta_ikari
	chara_auto	l_subuta,"“{.png"
endm
#- Î‚¢ ----------------------------------------------------------------------
macro	subuta_warai
	chara_auto	l_subuta,"Î.png"
endm
#- ‹Á‚« ----------------------------------------------------------------------
macro	subuta_odoroki
	chara_auto	l_subuta,"‹Á.png"
endm
#- ˆ£‚µ‚İ --------------------------------------------------------------------
macro	subuta_kanashimi
	chara_auto	l_subuta,"ˆ£.png"
endm
#- ‚É‚± ----------------------------------------------------------------------
macro	subuta_niko
	chara_auto	l_subuta,"‚É‚±.png"
endm

