## –és—§‚¿İ’è #############################################################
chara_folder	l_yakou,"chara"
chara_name	l_yakou,"–és"
@yakou_small
@yakou_shifuku

## Á‚· #######################################################################
macro	yakou_
	chara_off	l_yakou
endmacro

## ‹——£ #######################################################################
# ‰“‚¢
macro	yakou_small
	chara_size	l_yakou,"¬",0,-30
endm

# ’†ŠÔ
macro	yakou_middle
	chara_size	l_yakou,"’†",0,0
endm

# ‹ß‚¢
macro	yakou_large
	chara_size	l_yakou,"‘å",0,0
endm

## •‘• ######################################################################
macro	yakou_shifuku
	chara_clothes	l_yakou,"„•"
endm

macro	yakou_shifuku_damage
	chara_clothes	l_yakou,"„•oŒŒ"
endm


## •\î ######################################################################

#- •’Ê ----------------------------------------------------------------------
macro	yakou
	chara_auto	l_yakou,"•.png"
endm
#- Î‚¢ ----------------------------------------------------------------------
macro	yakou_warai
	chara_auto	l_yakou,"Î.png"
endm
#- “{‚è ----------------------------------------------------------------------
macro	yakou_ikari
	chara_auto	l_yakou,"“{.png"
endm
#- ‹Á‚« ----------------------------------------------------------------------
macro	yakou_odoroki
	chara_auto	l_yakou,"‹Á.png"
endm
#- ˆ£‚µ‚İ --------------------------------------------------------------------
macro	yakou_kanashimi
	chara_auto	l_yakou,"ˆ£.png"
endm
#- Šì‚Ñ --------------------------------------------------------------------
macro	yakou_yorokobi
	chara_auto	l_yakou,"Šì.png"
endm
#- ‰e --------------------------------------------------------------------
macro	yakou_kage
	chara_auto	l_yakou,"‰e.png"
endm
