ichigo_x	=	0
ichigo_y	=	0

## いちご大 ###################################################################
## 通常 center
macro	ichigon_c
	ichigo_x=80
	ichigo_y=0
	@_ichigon
endm

## 笑い center
macro	ichigon_c_warai
	ichigo_x=80
	ichigo_y=0
	@_ichigon_warai
endm


## 怒り center
macro	ichigon_c_ikari
	ichigo_x=80
	ichigo_y=0
	@_ichigon_ikari
endm

## 喜び center
macro	ichigon_c_yorokobi
	ichigo_x=80
	ichigo_y=0
	@_ichigon_yorokobi
endm

## 驚き center
macro	ichigon_c_akire
	ichigo_x=80
	ichigo_y=0
	@_ichigon_akire
endm

## 驚き center
macro	ichigon_c_odoroki
	ichigo_x=80
	ichigo_y=0
	@_ichigon_odoroki
endm

## 汗 center
macro	ichigon_c_ase
	ichigo_x=80
	ichigo_y=0
	@_ichigon_ase
endm

## 泣き center
macro	ichigon_c_naki
	ichigo_x=80
	ichigo_y=0
	@_ichigon_naki
endm

## 苦しい center
macro	ichigon_c_kurushii
	ichigo_x=80
	ichigo_y=0
	@_ichigon_kurushii
endm

#-----------------------------------------------------------------------------
## 普通
macro	_ichigon
	chara	l_ichigo,"chara\いちご大\いちご_私服_大_普通.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 笑い
macro	_ichigon_warai
	chara	l_ichigo,"chara\いちご大\いちご_私服_大_笑.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 怒り
macro	_ichigon_ikari
	chara	l_ichigo,"chara\いちご大\いちご_私服_大_怒.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 呆れ
macro	_ichigon_akire
	chara	l_ichigo,"chara\いちご大\いちご_私服_大_呆れ.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 放心
macro	_ichigon_houshin
	chara	l_ichigo,"chara\いちご大\いちご_私服_大_放心.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 欲情_喜び
macro	_ichigon_yokujou_yorokobi
	chara	l_ichigo,"chara\いちご大\いちご_私服_大_欲情_喜.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 欲情
macro	_ichigon_yokujou
	chara	l_ichigo,"chara\いちご大\いちご_私服_大_欲情_普通.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 照れ
macro	_ichigon_tere
	chara	l_ichigo,"chara\いちご大\いちご_私服_大_照れ.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 困る
macro	_ichigon_komaru
	chara	l_ichigo,"chara\いちご大\いちご_私服_大_困.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 苦しい
macro	_ichigon_kurushii
	chara	l_ichigo,"chara\いちご大\いちご_私服_大_苦.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 驚き
macro	_ichigon_odoroki
	chara	l_ichigo,"chara\いちご大\いちご_私服_大_驚.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 泣き
macro	_ichigon_naki
	chara	l_ichigo,"chara\いちご大\いちご_私服_大_泣.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 喜び
macro	_ichigon_yorokobi
	chara	l_ichigo,"chara\いちご大\いちご_私服_大_喜.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 企み
macro	_ichigon_takurami
	chara	l_ichigo,"chara\いちご大\いちご_私服_大_企み.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 汗
macro	_ichigon_ase
	chara	l_ichigo,"chara\いちご大\いちご_私服_大_汗.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 哀しみ
macro	_ichigon_kanashimi
	chara	l_ichigo,"chara\いちご大\いちご_私服_大_哀.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## コミカル怒り
macro	_ichigon_komikaru_ikari
	chara	l_ichigo,"chara\いちご大\いちご_私服_大_コミカル怒.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## コミカル笑い
macro	_ichigon_komikaru_warai
	chara	l_ichigo,"chara\いちご大\いちご_私服_大_コミカル笑.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## コミカル驚き
macro	_ichigon_komikaru_odoroki
	chara	l_ichigo,"chara\いちご大\いちご_私服_大_コミカル驚.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm


## いちご小 ###################################################################
## 通常 center
macro	ichigof_c
	ichigo_x=200
	ichigo_y=74
	@_ichigof
endm

## 通常 left
macro	ichigof_l
	ichigo_x=60
	ichigo_y=74
	@_ichigof
endm

## 通常 right
macro	ichigof_r
	ichigo_x=400
	ichigo_y=74
	@_ichigof
endm

## 通常 right
macro	ichigof_r_warai
	ichigo_x=400
	ichigo_y=74
	@_ichigof_warai
endm

#-----------------------------------------------------------------------------
## 普通
macro	_ichigof
	chara	l_ichigo,"chara\いちご小\いちご_私服_小_普通.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 笑い
macro	_ichigof_warai
	chara	l_ichigo,"chara\いちご小\いちご_私服_小_笑.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 怒り
macro	_ichigof_ikari
	chara	l_ichigo,"chara\いちご小\いちご_私服_小_怒り.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 呆れ
macro	_ichigof_akire
	chara	l_ichigo,"chara\いちご小\いちご_私服_小_呆れ.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 放心
macro	_ichigof_houshin
	chara	l_ichigo,"chara\いちご小\いちご_私服_小_放心.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 欲情_喜び
macro	_ichigof_yokujou_yorokobi
	chara	l_ichigo,"chara\いちご小\いちご_私服_小_欲情_喜.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 欲情
macro	_ichigof_yokujou
	chara	l_ichigo,"chara\いちご小\いちご_私服_小_欲情_普通.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 照れ
macro	_ichigof_tere
	chara	l_ichigo,"chara\いちご小\いちご_私服_小_照れ.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 困る
macro	_ichigof_komaru
	chara	l_ichigo,"chara\いちご小\いちご_私服_小_困.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 苦しい
macro	_ichigof_kurushii
	chara	l_ichigo,"chara\いちご小\いちご_私服_小_苦.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 驚き
macro	_ichigof_odoroki
	chara	l_ichigo,"chara\いちご小\いちご_私服_小_驚.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 泣き
macro	_ichigof_naki
	chara	l_ichigo,"chara\いちご小\いちご_私服_小_泣.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 喜び
macro	_ichigof_yorokobi
	chara	l_ichigo,"chara\いちご小\いちご_私服_小_喜.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 企み
macro	_ichigof_takurami
	chara	l_ichigo,"chara\いちご小\いちご_私服_小_企み.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 汗
macro	_ichigof_ase
	chara	l_ichigo,"chara\いちご小\いちご_私服_小_汗.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## 哀しみ
macro	_ichigof_kanashimi
	chara	l_ichigo,"chara\いちご小\いちご_私服_小_哀.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## コミカル怒り
macro	_ichigof_komikaru_ikari
	chara	l_ichigo,"chara\いちご小\いちご_私服_小_コミカル怒.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## コミカル笑い
macro	_ichigof_komikaru_warai
	chara	l_ichigo,"chara\いちご小\いちご_私服_小_コミカル笑.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm

## コミカル驚き
macro	_ichigof_komikaru_odoroki
	chara	l_ichigo,"chara\いちご小\いちご_私服_小_コミカル驚.png"
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm


















## いちご立ち設定 #############################################################
@ichigo_center
@ichigo_far
@ichigo_shifuku

## 消す #######################################################################
macro	ichigo_
	layer_release	l_ichigo
endmacro

## 場所 #######################################################################
# 中央
macro	ichigo_center
	ichigo_position=0
endm

# 左
macro	ichigo_left
	ichigo_position=1
endm

# 右
macro	ichigo_right
	ichigo_position=2
endm

#距離にあわせて位置を決定
macro	ichigo_pos
	if ichigo_distance=0 then goto _ichigo_pos_01
	if ichigo_distance=1 then goto _ichigo_pos_02
	if ichigo_distance=2 then goto _ichigo_pos_03

#距離遠い
label	_ichigo_pos_01
	if ichigo_position=0 then goto _ichigo_pos_01_center
	if ichigo_position=1 then goto _ichigo_pos_01_left
	if ichigo_position=2 then goto _ichigo_pos_01_right
	#中央
label	_ichigo_pos_01_center
	ichigo_x=200
	ichigo_y=74
	goto	_ichigo_pos_skip
	#左
label	_ichigo_pos_01_left
	ichigo_x=50
	ichigo_y=74
	goto	_ichigo_pos_skip
	#右
label	_ichigo_pos_01_right
	ichigo_x=350
	ichigo_y=74
	goto	_ichigo_pos_skip

#距離中間
label	_ichigo_pos_02
	if ichigo_position=0 then goto _ichigo_pos_02_center
	if ichigo_position=1 then goto _ichigo_pos_02_left
	if ichigo_position=2 then goto _ichigo_pos_02_right
	#中央
label	_ichigo_pos_02_center
	ichigo_x=200
	ichigo_y=98
	goto	_ichigo_pos_skip
	#左
label	_ichigo_pos_02_left
	ichigo_x=50
	ichigo_y=98
	goto	_ichigo_pos_skip
	#右
label	_ichigo_pos_02_right
	ichigo_x=350
	ichigo_y=98
	goto	_ichigo_pos_skip

#距離近い
label	_ichigo_pos_03
	if ichigo_position=0 then goto _ichigo_pos_03_center
	if ichigo_position=1 then goto _ichigo_pos_03_left
	if ichigo_position=2 then goto _ichigo_pos_03_right
	#中央
label	_ichigo_pos_03_center
	ichigo_x=200
	ichigo_y=98
	goto	_ichigo_pos_skip
	#左
label	_ichigo_pos_03_left
	ichigo_x=50
	ichigo_y=98
	goto	_ichigo_pos_skip
	#右
label	_ichigo_pos_03_right
	ichigo_x=350
	ichigo_y=98
	goto	_ichigo_pos_skip

label	_ichigo_pos_skip

endm


## 距離 #######################################################################
# 遠い
macro	ichigo_far
	ichigo_distance=0
endm

# 近い
macro	ichigo_near
	ichigo_distance=1
endm

# 中間
macro	ichigo_middle
	ichigo_distance=2
endm

## 服装 ######################################################################
#私服
macro	ichigo_shifuku
	ichigo_clothes=0
endm

#制服
macro	ichigo_fuyufuku
	ichigo_clothes=1
endm

#裸
macro	ichigo_hadaka
	ichigo_clothes=2
endm

#部屋着
macro	ichigo_heyagi
	ichigo_clothes=3
endm


## 表情 ######################################################################

#- 普通 ----------------------------------------------------------------------
macro	ichigo
if	ichigo_clothes=1 then goto _ichigo_01
if	ichigo_clothes=2 then goto _ichigo_02
if	ichigo_clothes=3 then goto _ichigo_03

#私服
label	_ichigo_00
	chara	l_ichigo,"chara\いちご小\いちご_私服_小_普通.png"
	goto _ichigo_s
#制服
label	_ichigo_01
	chara	l_ichigo,"chara\いちご小\いちご_冬服_小_普通.png"
	goto _ichigo_s
#裸
label	_ichigo_02
	chara	l_ichigo,"chara\ざくろ\小\裸\普.png"
	goto _ichigo_s
#部屋着
label	_ichigo_03
	chara	l_ichigo,"chara\ざくろ\小\部屋着\普.png"
	goto _ichigo_s

label	_ichigo_s
	@ichigo_pos
	layer_position_set	l_ichigo,ichigo_x,ichigo_y
endm




