## ”ü‰J—§‚¿İ’è #############################################################
chara_folder	l_kurofuku,"chara"
chara_name	l_kurofuku,"••"
@kurofuku_small
@kurofuku_shifuku

## Á‚· #######################################################################
macro	kurofuku_
	chara_off	l_kurofuku
endmacro

## ‹——£ #######################################################################
# ‰“‚¢
macro	kurofuku_small
	chara_size	l_kurofuku,"¬",0,0
endm

# ’†ŠÔ
macro	kurofuku_middle
	chara_size	l_kurofuku,"’†",0,0
endm

# ‹ß‚¢
macro	kurofuku_large
	chara_size	l_kurofuku,"‘å",0,0
endm

## •‘• ######################################################################
#„•
macro	kurofuku_shifuku
	chara_clothes	l_kurofuku,"„•"
endm

## •\î ######################################################################

#- •’Ê ----------------------------------------------------------------------
macro	kurofuku
	chara_auto	l_kurofuku,"•.png"
endm
#- “{ ------------------------------------------------------------------------
macro	kurofuku_ikari
	chara_auto	l_kurofuku,"“{.png"
endm


